version: '3.9'

services:
  covport:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./src/Server/Api/appsettings.Development.json
        target: /app/appsettings.json
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=&Nichrodon1
      - ACCEPT_EULA=1